// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1129:Do not use default value type constructor", Justification = "Unrequired.", Scope = "member", Target = "~M:Server.PipeServer.ListenForClients")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "When trying to export passwordHash and salt with AddRecord() received a ExceptionUnable to translate Unicode character exception.", Scope = "member", Target = "~F:Server.ServerForm.Utf8Encoder")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Unrequired.", Scope = "member", Target = "~M:Server.PipeServer.SendMessage(System.Byte[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Unrequired.", Scope = "member", Target = "~M:Server.ServerForm.UserLogin(System.Int32,System.String,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static elements should appear before instance elements", Justification = "Unrequired.", Scope = "member", Target = "~F:Server.ServerForm.userRepo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static elements should appear before instance elements", Justification = "Unrequired.", Scope = "member", Target = "~M:Server.ServerForm.MergeSort(System.Collections.Generic.List{System.Int32})~System.Collections.Generic.List{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "Form Event.", Scope = "member", Target = "~M:Server.ServerForm.pipeServer_ClientDisconnected")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "Form Event.", Scope = "member", Target = "~M:Server.ServerForm.btnStart_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "Form Event.", Scope = "member", Target = "~M:Server.ServerForm.btnCreate_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "Form Event.", Scope = "member", Target = "~M:Server.ServerForm.btnSearch_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "Form Event.", Scope = "member", Target = "~M:Server.ServerForm.btnExportCSV_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "Require to export to CSV.", Scope = "member", Target = "~F:Server.ServerForm.utf8Encoder")]